### PR TITLE
updated trading smart contract

### PR DESCRIPTION
**Pull request by Abchoudhary2512**
I created a smart contract that provides the basic infrastructure for P2P, P2G, and G2P energy trading. Users can initiate trades, and when both parties agree, the trade can be settled automatically and it is gas efficient and deployed on Polygon Mumbai Testnet and also I created the readme file for reference.

### CODE REVIEW

**Review by Kali-Decoder — COMMENTED** [review]
require(energyToken.transferFrom(trade.buyer, trade.seller, trade.energyAmount), "Energy transfer failed");
        require(energyToken.transferFrom(trade.seller, trade.buyer, totalCost), "Payment transfer failed"); In the first call we are transferring energy tokens from buyer to seller and on the next line we are transferring again energy tokens from seller to buyer it's like the seller is getting (totalCost- energyAmount) tokens and buyer Null . Instead of this, you can transfer money in the wallet of the seller using msg.value = totalCost . Let me know if any doubt .

**Comment by Abchoudhary2512** [comment]
Okay ! I will update it and requesting PR again!!

**Comment by Abchoudhary2512** [comment]
I have updated the .sol file !! please review it !

**Review by Kali-Decoder — COMMENTED** [review]
SettleTrade Function Should Be Payable .

**Review by Kali-Decoder — APPROVED** [review]

**Pull request merged**
